### ISSUE TITLE
Support pre and post build hooks

### ISSUE THREAD

**Issue by alexguerra-luizalabs** [luizalabs/teresa#133]
Useful for migrations for instance.

**Comment by drgarcia1986** [comment]
I'm working with an experimental "hooks" based on slugbuilder hooks, but, with a "teresa interface" (i.e. teresa.yaml). You can check [here](https://github.com/luizalabs/teresa-cli/compare/eap-breaking-change...dg-hooks)

**Comment by drgarcia1986** [comment]
Done by `release command` feature and different deploy hooks can be implemented by Slugbuilder and buildpacks stuff.
