### ISSUE TITLE
Support the creation of databases and caches as a service

### ISSUE THREAD

**Issue by alexguerra-luizalabs** [luizalabs/teresa#152]

**Comment by drgarcia1986** [comment]
Is it a good idea to build a DaaS inside of Teresa?

**Comment by alexguerra-luizalabs** [comment]
I think we can discuss the high level architecture here, keeping in mind that aws
probably will be the ultimate provider for now.

**Comment by alexguerra-luizalabs** [comment]
The cli may talk to the api just to get (and cache) DaaS related info, from that it is cli <--> DaaS. What do you think?

**Comment by drgarcia1986** [comment]
Makes sense, but, I think the better approach is create something like "Teresa DaaS" and the Teresa API working with it.

**Comment by alexguerra-luizalabs** [comment]
:+1:  one level of indirection is almost always good.

**Comment by aguerra** [comment]
Closed in favor of #374.
