### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by jairhenrique** [luizalabs/teresa#347]
As a teresa user
I want to access the shell from a pod
To run cli commands from my app

**Comment by drgarcia1986** [comment]
What about running a command without an interactive shell inside of a pod?

**Comment by jairhenrique** [comment]
>What about running a command without an interactive shell inside of a pod?

I think it's good enough, for now!

**Comment by drgarcia1986** [comment]
`teresa exec` command will be delivery in the next version, stay alert 😄
