### ISSUE TITLE
.teresaignore doesn't works like .gitignore

### ISSUE THREAD

**Issue by jairhenrique** [luizalabs/teresa#451]
# Scenario

```
# .gitignore
composer.phar
vendor/
```

```
# .teresaignore
composer.phar
vendor/
```

When I run `git status` the folder `vendor/` are not listed on my shell output, but when I do a deploy on Teresa, I see this message:

```shell
!     WARNING: Your Composer vendor dir is part of your Git repository.
       This directory should not be under version control; only your
       'composer.json' and 'composer.lock' files should be added, which
       will let Composer handle installation of dependencies on deploy.
       To suppress this notice, first remove the folder from your index
       by running 'git rm -r --cached vendor/'.
       Next, edit your project's '.gitignore' file and add the folder
       '/vendor/' to the list.
       For more info, refer to the Composer FAQ: http://bit.ly/1rlCSZU
```

So, `Teresa` are including the folder `vendor`  on tarball for deploy.

---

Changing `.teresaignore` to this: 
```
composer.phar
vendor
```
vendor folder are not include and the buildpack install my dependencies.

**Comment by drgarcia1986** [comment]
Thank you @jairhenrique, I'll check 👍

**Comment by drgarcia1986** [comment]
Again @jairhenrique, thank you for the report.

`.teresaignore` doesn't works like `.gitignore`, `.teresaignore` uses the glob pattern (`.gitignore` also uses, but is more intelligent LOL), but I saw that Teresa checks directories in the same way of a regular file (i.e. without a slash on end), I can add a slash in end of each directory name before check the pattern, will that change help you?

**Comment by drgarcia1986** [comment]
Ok, there are more problems with `.teresaignore`, f.ex, ignore a file inside a directory.
I'm looking for a solution to theses problems
