### ISSUE TITLE
Broken deploy shown as completed when out of resources 

### ISSUE THREAD

**Issue by aguerra** [luizalabs/teresa#464]
When there's no resources for the build pod the deploy proceeds and it is shown as completed:

Deploying app "myapp" to the cluster "mycluster"...
Are you sure? (yes/NO)? yes
Generating tarball of: .
Sending app tarbal...
Running release command
Exposing service
The app myapp has been successfully deployed

The result is pending build and release pods and a broken app  (no slug).

**Comment by drgarcia1986** [comment]
Maybe timeout waiting for a pending pod and we check if the deploy was finished per closed stream or a message in error channel :/
