### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [luizalabs/teresa#506]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by drgarcia1986** [comment]
Hi @jbeguna04 thank you!
For now, we have some doubts about version 1.0 and the future of project (and correct name), for this reason, we trying to avoid logos and domains with name `teresa`, but, thanks for ask.
