### ISSUE TITLE
List secrets set based on the ones that are currently on the k8s secrets

### ISSUE THREAD

**Issue by vinicyusmacedo** [luizalabs/teresa#587]
I set incorrectly a secret, say `bar` instead of `foo` and, in order to correct it, I have removed it directly from the cluster's secrets. 

While deploying, teresa still uses this old secret during deployment, even if I run `teresa app secret-unset`.
Also, there's no way to list the secrets that are currently set, so I have to unset them blindly.

**Comment by drgarcia1986** [comment]
Teresa sets secrets (and env vars) with metadata on the app namespace and Teresa uses this metadata to mount secrets, so if you remove secrets directly you'll crash the deploy.
This is a security flow to avoid devs to get others secrets on namespace (e.g. storage credentials)

**Comment by vinicyusmacedo** [comment]
Great, I get it. 

If this happens again, will it work if I, by using kubectl, remove the env variable from the annotations on the app namespace?

**Comment by drgarcia1986** [comment]
Yes 👍
