### ISSUE TITLE
Opening Teresa on Windows prompt

### ISSUE THREAD

**Issue by jackwesleymoreira** [luizalabs/teresa#606]
When I open a Teresa Cluster on a Windows Prompt, it appears special characters at the begin and at the end of each line.
![image](https://user-images.githubusercontent.com/41389597/62490058-cfc4ae80-b79e-11e9-9ea5-e4c3dc64522d.png)

**Comment by drgarcia1986** [comment]
@jackwesleymoreira I recommend you to use Teresa in powershell on windows. Those characters was the colors schema (compatible with classes Unix shell and windows PowerShell)
